[package]
name = "colog"
version = "1.4.0"
authors = ["Christian Iversen <ci@iversenit.dk>"]
description = "The `colog` library is a simple formatter backend for the standard rust logging system (in the `log` crate)."
repository = "https://github.com/chrivers/rust-colog"
readme = "README.md"
categories = ["value-formatting", "command-line-interface", "development-tools"]
keywords = ["cli", "terminal", "logging", "log", "color"]
license = "LGPL-3.0-only"
edition = "2024"

[lints.rust]
unstable_features = "forbid"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[lints.clippy]
all         = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
pedantic    = { level = "warn", priority = -1 }
cargo       = { level = "warn", priority = -1 }
nursery     = { level = "warn", priority = -1 }
perf        = { level = "warn", priority = -1 }
style       = { level = "warn", priority = -1 }

#multiple_crate_versions = "allow"

[dependencies]
log = '^0.4'
env_logger = '0.11'
colored = '3'
